### ISSUE TITLE
Resolve dependencies from external package at build time

### ISSUE THREAD

**Issue by SimonDelmas** [DavidVujic/poetry-multiproject-plugin#37]
First of all, thank you for this plugin, which I find very useful.

I have a use case that I'd love to be able to handle with this plugin. I have a package outside of my project root, that have its own dependencies. I include it in my project using your plugin and if currently if is well embedded at build time, the additional dependencies are not added / resolved. The final package cannot therefore be installed correctly. 

I found a plugin for ngx that do what I wish for here : https://betterprogramming.pub/poetry-python-nx-monorepo-5750d8627024 but I would like to avoid using ngx to manage Python project.

A solution (which is the solution used by the ngx plugin) could be to parse the dependencies from the foreign package and "poetry add" them in the temporary copy of the package at build time. 

Is this request something you could consider adding to this plugin? If so, I could give a try, but I'm not familiar with poetry plugins yet.

Thank for your attention.

Regards,

Simon

**Comment by DavidVujic** [comment]
Hi @SimonDelmas and thank you for posting this request!

If I understand it correctly, is the package you include in your project a separate Python project with its own third-party library dependencies?

Would this built-in feature of Poetry work for your use case? Here, an entire Python project is added as a dependency, just like a library.

https://python-poetry.org/docs/dependency-specification/#path-dependencies

**Comment by DavidVujic** [comment]
I think I understand @SimonDelmas 😄 , thank you for explaining!

The Multiproject plugin was built to include shared code into one or more projects within a monorepo. Currently, the individual project itself is meant to be managing the third-party dependencies (i.e. libraries), since the shared code is included as what Poetry calls "packages".

Wouldn't including the libraries as dependency with paths solve your issue (the link I posted in the previous response)? It should then resolve the dependencies for each of you libraries, if I'm not mistaking, and you should be able to use the code just as any dependency.

**Comment by SimonDelmas** [comment]
I must have misunderstood your previous answer! I'll look into it a bit further.

Thanks for your comment.

**Comment by MateoSaezMata** [comment]
Hi! The plugin is wonderful, honestly save a lot of rework!

I think @SimonDelmas made a fair point:
- If we build some main_project which depends on dep_project (both local and at different namespaces) using `poetry build-project` (following the docs: setting packages under [tool.poetry]) we can import some module from dep_project into main_project.
- The issue here is that dep_project depends on some_lib (and is avaliable in pypi) the `poetry build-project` doesn´t resolve the some_lib dependency, so we have to add the some_lib dependency into main_project pyproject.toml.

Am I right?

**Comment by DavidVujic** [comment]
Hi @MateoSaezMata, I'm happy to hear that the plugin is useful!

Yes, the multproject-plugin makes it possible to reference Python namespace packages with a relative path and the `build-project` command will turn it into a proper wheel/sdist (with dependencies in a subfolder of the project).

You are right, it doesn't deal with third-party dependencies. Those will need to be added manually in the project needing them.

Are you a Polylith user? If so, there is tooling support there for checking and visualizing packages and dependencies, and will warn about any missing ones too. The Polylith plugin is built on top of this plugin, in a way.

**Comment by MateoSaezMata** [comment]
Thanks for your response @DavidVujic!

When I discovered your plugin and I read the docs I saw that you mention the Polylith... ¿Philosopy?

I will dig into the Polylith plugin and I let you know if I included it into my dev stack.

Thanks again!
