### ISSUE TITLE
Check-project generates boatload of permission denied errors

### ISSUE THREAD

**Issue by felixogg-britned** [DavidVujic/poetry-multiproject-plugin#38]
**Describe the bug**
After setting up a polylith repo, with a first base and component in it, the `check-project` command generated some fixes, on first run and none on second run. However on both runs it ends with a long list of permission denied errors.

**Error Log**
Export of console session (windows under poetry shell). I had to redact some content, but I think it clearly seems to be looking into .git subfolders, where I don't think it should go.
[scratch_1.txt](https://github.com/DavidVujic/poetry-multiproject-plugin/files/11915396/scratch_1.txt)

**Expected behavior**
Run without permission denied errors

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2
 - Python version: 3.11.2
 - Poetry version: 1.5.1

**Comment by DavidVujic** [comment]
Thank you for reporting this! It looks like there is a `.git` folder in there, that should have been ignored. I'll have a look.

Meanwhile, since you are a Polylith user, there is probably better ways to check the code. This command was developed later, and without the quite slow `mypy` checks that the `check-project` command does under the hood.

```
poetry poly check
```

More here: https://davidvujic.github.io/python-polylith-docs/commands/

**Comment by DavidVujic** [comment]
There's a new version of the Multiproject plugin out, hopefully solving your issues!
